/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Q2;

import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author curtc
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Practical
     */
    public Quiz() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        numOfQGroup = new javax.swing.ButtonGroup();
        timerGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        correctTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        triedTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        questionTxt = new javax.swing.JTextField();
        answerTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AddRad = new javax.swing.JRadioButton();
        subRad = new javax.swing.JRadioButton();
        divRad = new javax.swing.JRadioButton();
        multiRad = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        timeOnRad = new javax.swing.JRadioButton();
        timeOffRad = new javax.swing.JRadioButton();
        timerTxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RandomRad = new javax.swing.JRadioButton();
        Rad1 = new javax.swing.JRadioButton();
        Rad2 = new javax.swing.JRadioButton();
        Rad3 = new javax.swing.JRadioButton();
        Rad4 = new javax.swing.JRadioButton();
        Rad5 = new javax.swing.JRadioButton();
        Rad6 = new javax.swing.JRadioButton();
        Rad7 = new javax.swing.JRadioButton();
        Rad8 = new javax.swing.JRadioButton();
        Rad9 = new javax.swing.JRadioButton();
        exitBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        checkAnsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 350));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 255), null, null, new java.awt.Color(153, 0, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 20));

        correctTxt.setEditable(false);
        correctTxt.setBackground(new java.awt.Color(204, 204, 255));
        correctTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        correctTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correctTxt.setText("0");
        correctTxt.setBorder(null);
        correctTxt.setPreferredSize(new java.awt.Dimension(60, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(correctTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(correctTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 255), null, null, new java.awt.Color(153, 0, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(70, 20));

        triedTxt.setEditable(false);
        triedTxt.setBackground(new java.awt.Color(204, 204, 255));
        triedTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        triedTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        triedTxt.setText("0");
        triedTxt.setBorder(null);
        triedTxt.setPreferredSize(new java.awt.Dimension(60, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(triedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(triedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tried:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Correct:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));
        jPanel4.setPreferredSize(new java.awt.Dimension(380, 90));

        questionTxt.setEditable(false);
        questionTxt.setBackground(new java.awt.Color(204, 204, 255));
        questionTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        questionTxt.setText("Press start to begin");
        questionTxt.setBorder(null);

        answerTxt.setBackground(new java.awt.Color(204, 204, 255));
        answerTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        answerTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(questionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionTxt)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(answerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Type:");

        typeGroup.add(AddRad);
        AddRad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddRad.setText("Addition");

        typeGroup.add(subRad);
        subRad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subRad.setText("Subtraction");

        typeGroup.add(divRad);
        divRad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divRad.setText("Division");
        divRad.setToolTipText("");

        typeGroup.add(multiRad);
        multiRad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        multiRad.setText("Multiplication");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddRad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subRad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(divRad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(multiRad)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multiRad))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Timer");

        timerGroup.add(timeOnRad);
        timeOnRad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeOnRad.setText("On");

        timerGroup.add(timeOffRad);
        timeOffRad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeOffRad.setText("Off");

        timerTxt.setEditable(false);
        timerTxt.setBackground(new java.awt.Color(204, 204, 255));
        timerTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timerTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timerTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(timeOnRad))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(timeOffRad)))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timerTxt)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeOnRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeOffRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("No. of Questions");
        jLabel4.setDoubleBuffered(true);

        numOfQGroup.add(RandomRad);
        RandomRad.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        RandomRad.setText("Random");

        numOfQGroup.add(Rad1);
        Rad1.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad1.setText("1");

        numOfQGroup.add(Rad2);
        Rad2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad2.setText("2");

        numOfQGroup.add(Rad3);
        Rad3.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad3.setText("3");

        numOfQGroup.add(Rad4);
        Rad4.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad4.setText("4");

        numOfQGroup.add(Rad5);
        Rad5.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad5.setText("5");

        numOfQGroup.add(Rad6);
        Rad6.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad6.setText("6");

        numOfQGroup.add(Rad7);
        Rad7.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad7.setText("7");

        numOfQGroup.add(Rad8);
        Rad8.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad8.setText("8");

        numOfQGroup.add(Rad9);
        Rad9.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Rad9.setText("9");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Rad7)
                                .addGap(12, 12, 12)
                                .addComponent(Rad8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rad9))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Rad4)
                                .addGap(12, 12, 12)
                                .addComponent(Rad5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rad6))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RandomRad)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Rad1)
                                .addGap(12, 12, 12)
                                .addComponent(Rad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rad3)))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RandomRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rad1)
                    .addComponent(Rad2)
                    .addComponent(Rad3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rad4)
                    .addComponent(Rad5)
                    .addComponent(Rad6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rad7)
                    .addComponent(Rad8)
                    .addComponent(Rad9)))
        );

        exitBtn.setBackground(new java.awt.Color(153, 0, 204));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.setToolTipText("");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        startBtn.setBackground(new java.awt.Color(153, 0, 204));
        startBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Start");
        startBtn.setToolTipText("");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        checkAnsBtn.setBackground(new java.awt.Color(153, 0, 204));
        checkAnsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkAnsBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkAnsBtn.setText("Check Answer");
        checkAnsBtn.setToolTipText("");
        checkAnsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAnsBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(checkAnsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAnsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Random random = new Random();
    private double answ;
    private int qNum;
    private int counter;
    private int wrong;
    
    private int numOfQ(){
        int numQ = 0;
        if(RandomRad.isSelected()){
            numQ = random.nextInt();
        }
        else if(Rad1.isSelected()){
            numQ = 1;
        }
        else if(Rad2.isSelected()){
            numQ = 2;
        }
        else if(Rad3.isSelected()){
            numQ = 3;
        }
        else if(Rad4.isSelected()){
            numQ = 4;
        }
        else if(Rad5.isSelected()){
            numQ = 5;
        }
        else if(Rad6.isSelected()){
            numQ = 6;
        }
        else if(Rad7.isSelected()){
            numQ = 7;
        }
        else if(Rad8.isSelected()){
            numQ = 8;
        }
        else if(Rad9.isSelected()){
            numQ = 9;
        }
        return numQ;
    }
    
    private void question(){
        try{
            if(numOfQ() == 0){
                JOptionPane.showMessageDialog(null, "Please select number of questions");
            }
            else{
                int num1 = random.nextInt(10);
                int num2 = random.nextInt(10);
                double answer;

                if(AddRad.isSelected()){
                    answer = num1 + num2;
                    questionTxt.setText(num1 + " + " + num2);
                    answ = answer;
                }
                else if(subRad.isSelected()){
                    answer = num1 - num2;
                    questionTxt.setText(num1 + " - " + num2);
                    answ = answer;
                }
                else if(divRad.isSelected()){
                    answer = num1 / num2;
                    questionTxt.setText(num1 + " / " + num2);
                    answ = answer;
                }
                else if(multiRad.isSelected()){
                    answer = num1 * num2;
                    questionTxt.setText(num1 + " * " + num2);
                    answ = answer;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please select type of questions");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void clear(){
        answerTxt.setText("");
        questionTxt.setText("");
        correctTxt.setText("");
        triedTxt.setText("");
        typeGroup.clearSelection();
        numOfQGroup.clearSelection();
        timerGroup.clearSelection();
        timerTxt.setText("");
    }
    
    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        if(timeOffRad.isSelected()){
            qNum = 0;
            counter = 0;
            wrong = 0;
            question();
        }
        else if(timeOnRad.isSelected()){
            qNum = 0;
            counter = 0;
            wrong = 0;
            question();
            Timer timer = new Timer();

            timer.scheduleAtFixedRate(new TimerTask() {
                int i = 5 * numOfQ();

                public void run() {

                    timerTxt.setText(String.valueOf(i));
                    i--;

                    if (i < 0) {
                        timer.cancel();
                        JOptionPane.showMessageDialog(null, "Time Over");
                        JOptionPane.showMessageDialog(null, "The quiz is complpete\nYour score is " + counter + " out of " + numOfQ());
                        clear();
                    }
                }
            }, 0, 1000);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select timer option");
        }
        
    }//GEN-LAST:event_startBtnMouseClicked

    private void checkAnsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAnsBtnMouseClicked
        qNum++;
        double answer = Double.parseDouble(answerTxt.getText());
        if(answ == answer){
            counter++;
        }
        else{
            wrong++;
            JOptionPane.showMessageDialog(null, "The answer was: " + answ);
        }
        correctTxt.setText(String.valueOf(counter));
        triedTxt.setText(String.valueOf(wrong));
        if(qNum < numOfQ()){
            answerTxt.setText("");
            question();
        }
        else{
            questionTxt.setText("Quiz complete");
            answerTxt.setText("");
            if(timeOffRad.isSelected()){
                JOptionPane.showMessageDialog(null, "The quiz is complpete\nYour score is " + counter + " out of " + numOfQ());
                clear();
            }
        }
    }//GEN-LAST:event_checkAnsBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddRad;
    private javax.swing.JRadioButton Rad1;
    private javax.swing.JRadioButton Rad2;
    private javax.swing.JRadioButton Rad3;
    private javax.swing.JRadioButton Rad4;
    private javax.swing.JRadioButton Rad5;
    private javax.swing.JRadioButton Rad6;
    private javax.swing.JRadioButton Rad7;
    private javax.swing.JRadioButton Rad8;
    private javax.swing.JRadioButton Rad9;
    private javax.swing.JRadioButton RandomRad;
    private javax.swing.JTextField answerTxt;
    private javax.swing.JButton checkAnsBtn;
    private javax.swing.JTextField correctTxt;
    private javax.swing.JRadioButton divRad;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton multiRad;
    private javax.swing.ButtonGroup numOfQGroup;
    private javax.swing.JTextField questionTxt;
    private javax.swing.JButton startBtn;
    private javax.swing.JRadioButton subRad;
    private javax.swing.JRadioButton timeOffRad;
    private javax.swing.JRadioButton timeOnRad;
    private javax.swing.ButtonGroup timerGroup;
    private javax.swing.JTextField timerTxt;
    private javax.swing.JTextField triedTxt;
    private javax.swing.ButtonGroup typeGroup;
    // End of variables declaration//GEN-END:variables
}
